"""core 面向外部实现的协议（依赖倒置边界）。

core 只依赖这些 Protocol；具体实现由 app/ 层注入：
- Memory     -> memory.memory.AgentMemory
- LLMClient  -> llm.client.LLMClient
- Logger     -> core.logger.SimLogger 或任意带 logging 方法的对象
"""

from __future__ import annotations

from typing import Any, Protocol


class Logger(Protocol):
    def debug(self, message: str) -> None: ...
    def info(self, message: str) -> None: ...
    def warning(self, message: str) -> None: ...
    def error(self, message: str) -> None: ...


class Memory(Protocol):
    def add(self, event: str, tick: int = 0) -> None: ...
    def get_context(self) -> str: ...
    def recent(self, limit: int) -> list[dict]: ...
    async def compress(self, llm_client: Any, relationships: dict | None = None) -> dict | None: ...

    @property
    def needs_compression(self) -> bool: ...
    @property
    def short_term_size(self) -> int: ...
    @property
    def summary(self) -> str: ...
    def oldest_short_term_tick(self) -> int | None: ...


class LLMClient(Protocol):
    logger: Logger | None

    async def call(self, **kwargs) -> Any: ...
    async def call_multi(self, **kwargs) -> Any: ...
    async def call_json(self, **kwargs) -> Any: ...
